version: '3'

services:
  db: 
    container_name: db
    image: postgres:14-alpine3.17
    environment:
      POSTGRES_PASSWORD: 'password123'
      POSTGRES_USER: 'postgres'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
  server:
    image: server-example1
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: always
volumes:
  data:

